### ISSUE TITLE
 train_model.py  load dataset error

### ISSUE THREAD

**Issue by pczzy** [huggingface/olm-training#2]
I get  error ”You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead
“ when training  Robera 

and I notice the last line of chunk_and_tokenize_datasets.py save dataset to disk.

`tokenized_ds.save_to_disk(args.output_dataset_name)`

There is another question, if training distilled roberta , then how to set the --model_config_id parameter

**Here is my training process**
```bash
python create_tokenizer.py --input_dataset_names olm/wikipedia --existing_tokenizer_template roberta-base --output_tokenizer_name wikipedia-bpe-tokenizer --text_column text
```

```bash
python chunk_and_tokenize_datasets.py \
     --input_dataset_names olm/wikipedia \
     --input_tokenizer_name wikipedia-bpe-tokenizer \
     --output_dataset_name dataset/olm-wikipedia-zh-tokenized-512 \
     --text_column text \
     --num_proc 26  --max_len 512
```
python -m torch.distributed.launch --nproc_per_node=4 train_model.py --lm_type=mlm --dataset_id=dataset/olm-wikipedia-zh-tokenized-512 --tokenizer_id=wikipedia-bpe-tokenizer  --model_config_id=roberta-base --adam_beta2=0.98 --adam_epsilon=1e-6 --adam_beta1=0.9 --warmup_steps=24000 --max_steps=100000 --per_device_train_batch_size=16 --gradient_accumulation_steps=25 --learning_rate=6e-4

```
Traceback (most recent call last):
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 179, in <module>
Traceback (most recent call last):
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 179, in <module>
    train_model()
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 139, in train_model
    train_model()
      File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 139, in train_model
train_dataset = load_dataset(script_args.dataset_id, split="train")
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/datasets/load.py", line 1710, in load_dataset
    Traceback (most recent call last):
train_dataset = load_dataset(script_args.dataset_id, split="train")
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/datasets/load.py", line 1710, in load_dataset
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 179, in <module>
    train_model()
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 139, in train_model
        raise ValueError(
train_dataset = load_dataset(script_args.dataset_id, split="train")
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/datasets/load.py", line 1710, in load_dataset
ValueError: You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead.
    raise ValueError(
ValueError: You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead.
    raise ValueError(
ValueError: You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead.
Traceback (most recent call last):
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 179, in <module>
    train_model()
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/train_model.py", line 139, in train_model
    train_dataset = load_dataset(script_args.dataset_id, split="train")
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/datasets/load.py", line 1710, in load_dataset
    raise ValueError(
ValueError: You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead.
```

**Comment by TristanThrush** [comment]
Hi thanks for raising this issue. I'm sure that others will run into it too.

1. To solve the `load_from_disk` error, just delete the local dataset. The script is assuming that you have deleted the local tokenized dataset and it is stored on the hugging face hub. I will fix this soon so you can specify a local dataset too.

2. If you want to train a `distilroberta-base` on the normal masked language modeling objective like `roberta-base`, then I think everything should work if you specify `--model_config_id=distilroberta-base`. But this is not how the original `distilroberta-base` was trained. The original model was trained in a way that was specified [here](https://huggingface.co/distilroberta-base), using a pretrained `roberta-base` model as a teacher. If you want to get comparable results to `distilroberta-base`, then you'll probably have to follow this fancier training routine.

**Comment by pczzy** [comment]
It's works after some modification. train_model.py is a elegant and neat code.
