### ISSUE TITLE
huggingface-hub error

### ISSUE THREAD

**Issue by Muhtasham** [huggingface/olm-training#3]
Hi, 

When running train_model.py I got the error below,

```bash
Traceback (most recent call last):
  File "train_model.py", line 209, in <module>
    train_model()
  File "train_model.py", line 196, in train_model
    trainer = Trainer(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 489, in __init__
    self.init_git_repo(at_init=True)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 3284, in init_git_repo
    self.repo = Repository(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'private'
```

huggingface-hub which came with requirements.txt was 0.12.0, downgrading to 0.11.0 solved the issue, so fixing this version(0.11.0) in requirements.txt would be temporary fix.  

[Here](https://colab.research.google.com/drive/15T6qAEM8_ktZK5-N_h4D0APa6_EG9Hgh?usp=sharing) is the notebook to reproduce issue.

**Comment by TristanThrush** [comment]
Thanks, I plan to address soon!
