### ISSUE TITLE
MLM pretrain model failed on fillmask task

### ISSUE THREAD

**Issue by pczzy** [huggingface/olm-training#4]
After train Roberta  from scratch via train_model.py

Using following script  test FillMask ability
```
from transformers import FillMaskPipeline, AutoTokenizer,AutoModel

model = AutoModel.from_pretrained("./roberta-wiki")
tokenizer = AutoTokenizer.from_pretrained("./roberta-wiki")
fill_masker = FillMaskPipeline(model=model,tokenizer=tokenizer)

print(fill_masker(f"This is a simple {tokenizer.mask_token}.",top_k=2))

```

Get an error , Anything missing ?

Some weights of the model checkpoint at ./roberta-wiki were not used when initializing RobertaModel: ['lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at ./roberta-wiki and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/data0/zhangpeng6/nanogpt/language-modeling-script/t.py", line 19, in <module>
    print(fill_masker(f"This is a simple {tokenizer.mask_token}.",top_k=2))
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 227, in __call__
    outputs = super().__call__(inputs, **kwargs)
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1074, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1082, in run_single
    outputs = self.postprocess(model_outputs, **postprocess_params)
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 98, in postprocess
    outputs = model_outputs["logits"]
  File "/data0/zhangpeng6/miniconda3/envs/olm/lib/python3.10/site-packages/transformers/utils/generic.py", line 263, in __getitem__
    return inner_dict[k]
KeyError: 'logits'

**Comment by pczzy** [comment]
solved
